## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

#### < numpy array의 특징 >

1. 모든 원소의 dtype이 같다.

2. 연산의 의마가 조금 다르다. (broadcasting)

3. 대용량 array인 경우에 for 문을 직접 사용하는 것보다 내부적으로 정의된 연산을 사용하는게 더 빠르다.

4. 생성 후에 크기 변경이 불가능하다. (c의 array와 동일)

### 1.1. Numpy Array creation

In [2]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [3]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4]

In [4]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1, 2], 
         [3, 4]]

In [8]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
arr1 = np.array(data)
arr1

array([1, 2, 3, 4])

In [9]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2

array([[1, 2],
       [3, 4]])

In [10]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [13]:
# shape이 (10, 0)인 원소로 0을 갖는 array
np.zeros(shape=(10, ))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# [start, stop]에서 num개의 number를 균등한 구간으로 잘라서 원소를 생성
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [17]:
# 주어진 shape을 가지는 numpy array를 만들어주는데, 원소는 표준정규분포에서 sampling.
np.random.randn(10, )

array([ 0.79973666, -1.37301473,  1.20944909, -0.72664615, -0.26555056,
        1.93013274, -0.05482627, -0.37533035, -1.13067837,  1.49419592])

### 1.2. Reshaping array

In [19]:
# 3 x 3 행렬을 만들어봅시다.
# 1차원: vector
# 2차원: matrix
# 3차원 이상: tensor
# shape은 가장 바깥 괄호부터 원소의 개수를 순차적으로 기록한 것으로 정의.
x = np.zeros(shape=(3, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# 224 x 224 크기의 3개(RGB) channel을 가지고 있는이미지가 32개,
np.zeros(shape=(32, 3, 224, 224))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0.

In [21]:
# reshape을 이용하여 만들어봅시다.
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# (9, ) != (9, 1)
np.arange(1, 10).reshape(9, ) # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(1, 10).reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
# shape자리에 -1을 넣어서 알아서 size를 조정하게 할 수 있다.
np.arange(1, 21).reshape(4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### 1.3. Concatenation of arrays

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?

# arr1와 arr2를 합칩니다
arr1 + arr2

array([5, 7, 9])

In [29]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [31]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))

In [32]:
# 리스트로 더하기 연산해보기
v1 + v2

array([5, 7, 9])

In [33]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [34]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [35]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [37]:
# dot product
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [38]:
arr1 = np.array([1, 2, 3])

In [49]:
arr2 = np.array([[-1, -1, -1],
                [1, 1, 1]])

In [50]:
# 2개의 array를 더해보면?
arr1 + arr2 # (3, ) + (2, 3)
# (5, ) + (3, 4, 5) (V)
# (3, 4) + (5, 3, 4) (V)
# (3, 4) + (3, 4, 5) (X)

array([[0, 1, 2],
       [2, 3, 4]])

In [51]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [ ]:
# int -> float
arr1 / 1

In [54]:
# f = lambda x : 1/x
1 / arr1 # 각 원소를 reverse 연산

array([1.        , 0.5       , 0.33333333])

In [53]:
# f = lambda x : x + 2
arr1 + 2

array([3, 4, 5])

### 1.6. Indexing


In [65]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 첫번째 원소
arr1[1]

1

In [67]:
# 마지막 원소
arr1[-1]

9

In [68]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [69]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
# arr2의 2row, 3column 원소 = 7
arr2[1, 2]

7

In [75]:
# arr2의 세번째 column [3, 7, 11]
arr2[:, 2]

array([ 3,  7, 11])

In [76]:
# arr2의 두번째 row
arr2[1]

array([5, 6, 7, 8])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [57]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
np.random.seed(42) # set seed number
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [58]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [59]:
# mat1 제곱하기
np.square(mat1)

array([[0.24672495, 0.01911702, 0.41950044],
       [2.31961994, 0.0548278 , 0.05482011],
       [2.49391312, 0.58895606, 0.2204062 ],
       [0.2943714 , 0.21475596, 0.2169042 ],
       [0.05854574, 3.66064129, 2.97534153]])

In [77]:
# mat1의 제곱근 구하기
np.sqrt(mat1.astype('complex')) # 복소수 구분: j가 허수부분

array([[0.70477951+0.j        , 0.        +0.37183908j,
        0.80479099+0.j        ],
       [1.23411096+0.j        , 0.        +0.48389397j,
        0.        +0.48387701j],
       [1.25666734+0.j        , 0.87603352+0.j        ,
        0.        +0.68518201j],
       [0.73658675+0.j        , 0.        +0.68074789j,
        0.        +0.68244396j],
       [0.49189661+0.j        , 0.        +1.38321374j,
        0.        +1.31336127j]])

In [81]:
# linear algebra functions
vec = np.array([1, 2, 3])

# 1. norm
print(np.linalg.norm(vec))

# 2. eigenvalue
mat = np.array([[1, 0],
               [0, 1]])
print(np.linalg.eig(mat))

3.7416573867739413
EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))


### 2.2. Aggregation functions 

In [85]:
np.random.seed(0xC0FFEE)
mat2 = np.random.rand(3, 2)
mat2

array([[0.57290783, 0.81519505],
       [0.92585076, 0.09358959],
       [0.26716135, 0.96059676]])

In [87]:
# Summation
print(np.sum(mat2)) # 전체합
print(np.sum(mat2 , axis=0)) # 0: 세로방향 합
print(np.sum(mat2 , axis=1)) # 1: 가로방향 합

3.635301352873192
[1.76591995 1.86938141]
[1.38810288 1.01944035 1.22775812]


In [88]:
# mean
np.mean(mat2, axis=0)

array([0.58863998, 0.62312714])

In [89]:
# std
np.std(mat2, axis=1)

array([0.12114361, 0.41613058, 0.3467177 ])

In [91]:
# min, max
print(np.min(mat2, axis=0))
print(np.max(mat2, axis=1))

[0.26716135 0.09358959]
[0.81519505 0.92585076 0.96059676]


In [92]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0)

array([2, 1])

In [93]:
# 최대값이 있는 Index
np.argmax(mat2, axis=1)

array([1, 0, 1])

In [94]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2)

array([[0.57290783, 0.81519505],
       [0.09358959, 0.92585076],
       [0.26716135, 0.96059676]])

In [ ]:
# index를 정렬


## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [95]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [103]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 1000000)

In [104]:
%timeit reverse_num(big_array)

CPU times: user 7.93 s, sys: 13.9 ms, total: 7.95 s
Wall time: 7.95 s


array([0.025     , 0.02702703, 0.2       , ..., 0.07692308, 0.02173913,
       0.01886792])

In [105]:
%timeit 1.0 / big_array # universal function이 훨씬 빠름

CPU times: user 9.45 ms, sys: 16.1 ms, total: 25.5 ms
Wall time: 24 ms


array([0.025     , 0.02702703, 0.2       , ..., 0.07692308, 0.02173913,
       0.01886792])